role_map = {
    "Great Tusk": "Hazard Removal",
    "Kingambit": "Sweeper",
    "Gholdengo": "Wallbreaker",
    "Dragapult": "Attacker",
    "Dragonite": "Sweeper",
    "Ogerpon-Wellspring": "Wallbreaker",
    "Iron Valiant": "Attacker",
    "Zamazenta": "Attacker",
    "Slowking-Galar": "Pivot",
    "Corviknight": "Pivot",
    "Gliscor": "Wall",
    "Raging Bolt": "Wallbreaker",
    "Hatterene": "Hazard Removal",
    "Landorus-Therian": "Pivot",
    "Cinderace": "Attacker",
    "Iron Treads": "Hazard Lead",
    "Alomomola": "Pivot",
    "Glimmora": "Hazard Lead",
    "Kyurem": "Wallbreaker",
    "Ceruledge": "Sweeper",
    "Samurott-Hisui": "Hazard Lead",
    "Scizor": "Pivot",
    "Ting-Lu": "Wall",
    "Darkrai": "Attacker",
    "Rillaboom": "Pivot",
    "Garganacl": "Wall",
    "Iron Moth": "Sweeper",
    "Zapdos": "Pivot",
    "Pecharunt": "Pivot",
    "Walking Wake": "Sun Sweeper",
    "Garchomp": "Hazard Stack",
    "Tyranitar": "Weather Setter",
    "Heatran": "Wallbreaker",
    "Primarina": "Pivot",
    "Clefable": "Pivot",
    "Moltres": "Pivot",
    "Enamorus": "Sweeper",
    "Deoxys-Speed": "Attacker",
    "Meowscarada": "Pivot",
    "Excadrill": "Sand Sweeper",
    "Weezing-Galar": "Pivot",
    "Iron Crown": "Pivot",
    "Torkoal": "Weather Setter",
    "Pelipper": "Weather Setter",
    "Dondozo": "Wall",
    "Toxapex": "Pivot",
    "Tornadus-Therian": "Pivot",
    "Hydrapple": "Wallbreaker",
    "Clodsire": "Wall",
    "Greninja": "Sweeper",
    "Blaziken": "Sweeper",
    "Ninetales-Alola": "Weather Setter",
    "Ursaluna": "Wallbreaker",
    "Serperior": "Sweeper",
    "Araquanid": "Hazard Lead",
    "Hoopa-Unbound": "Wallbreaker",
    "Blissey": "Wall",
    "Weavile": "Wallbreaker",
    "Ninetales": "Weather Setter",
    "Skeledirge": "Wall",
    "Lokix": "Wallbreaker",
    "Rotom-Wash": "Pivot",
    "Quaquaval": "Sweeper",
    "Latios": "Wallbreaker",
    "Sinistcha": "Utility",
    "Venusaur": "Sweeper",
    "Tinkaton": "Utility",
    "Grimmsnarl": "Utility",
    "Iron Hands": "Pivot",
    "Ribombee": "Hazard Lead",
    "Skarmory": "Wall",
    "Volcanion": "Wallbreaker",
    "Gengar": "Sweeper",
    "Goodra-Hisui": "Wall",
    "Barraskewda": "Sweeper",
    "Arcanine-Hisui": "Wallbreaker",
    "Mimikyu": "Sweeper",
    "Ogerpon-Cornerstone": "Sweeper",
    "Zoroark-Hisui": "Wallbreaker",
    "Hawlucha": "Sweeper",
    "Ogerpon": "Wallbreaker",
    "Umbreon": "Wall",
    "Keldeo": "Wallbreaker",
    "Metagross": "Wallbreaker",
    "Maushold": "Hazard Removal",
    "Polteageist": "Sweeper",
    "Iron Boulder": "Sweeper",
    "Incineroar": "Pivot",
    "Indeedee": "Utility",
    "Moltres-Galar": "Sweeper",
    "Slither Wing": "Wallbreaker",
    "Azumarill": "Wallbreaker",
    "Thundurus-Therian": "Sweeper",
    "Latias": "Sweeper",
    "Gyarados": "Sweeper",
    "Kommo-o": "Sweeper",
    "Hydreigon": "Wallbreaker",
    "Cresselia": "Wall",
    "Cloyster": "Sweeper",
    "Mandibuzz": "Pivot",
    "Comfey": "Sweeper",
    "Galvantula": "Hazard Lead",
    "Lilligant-Hisui": "Sweeper",
    "Gardevoir": "Wallbreaker",
    "Conkeldurr": "Wallbreaker",
    "Charizard": "Sweeper",
    "Talonflame": "Pivot",
    "Haxorus": "Sweeper",
    "Chesnaught": "Hazard Stack",
    "Blastoise": "Hazard Removal",
    "Jolteon": "Pivot",
    "Salamence": "Sweeper",
    "Kingdra": "Sweeper",
    "Mamoswine": "Wallbreaker",
    "Espeon": "Utility",
    "Okidogi": "Wallbreaker",
    "Milotic": "Wall",
    "Sandy Shocks": "Hazard Stack",
    "Magnezone": "Wallbreaker",
    "Manaphy": "Sweeper",
    "Amoonguss": "Wall",
    "Chandelure": "Wallbreaker",
    "Kleavor": "Hazard Lead",
    "Forretress": "Hazard Removal",
    "Armarouge": "Wallbreaker",
    "Jirachi": "Pivot",
    "Bronzong": "Wall",
    "Ditto": "Utility",
    "Toxicroak": "Sweeper",
    "Empoleon": "Hazard Removal",
    "Lucario": "Sweeper",
    "Infernape": "Pivot",
    "Whimsicott": "Utility",
    "Mew": "Utility",
    "Slowking": "Pivot",
    "Fezandipiti": "Pivot",
    "Muk-Alola": "Wall",
    "Snorlax": "Wall",
    "Chansey": "Wall",
    "Pawmot": "Wallbreaker",
    "Swampert": "Pivot",
    "Gastrodon": "Wall",
    "Reuniclus": "Sweeper",
    "Breloom": "Wallbreaker",
    "Salazzle": "Sweeper",
    "Gallade": "Sweeper",
    "Porygon2": "Wall",
    "Porygon-Z": "Sweeper",
    "Tentacruel": "Hazard Removal",
    "Sylveon": "Wall",
    "Hippowdon": "Weather Setter",
    "Regidrago": "Wallbreaker",
    "Krookodile": "Pivot",
    "Torterra": "Sweeper",
    "Zapdos-Galar": "Sweeper",
    "Sableye": "Utility",
    "Deoxys-Defense": "Hazard Lead",
    "Crawdaunt": "Wallbreaker",
    "Quagsire": "Wall",
    "Vaporeon": "Wall",
    "Toxtricity": "Wallbreaker",
    "Sceptile": "Sweeper",
    "Noivern": "Pivot",
    "Kilowattrel": "Pivot",
    "Bisharp": "Sweeper",
    "Donphan": "Hazard Removal",
    "Basculegion": "Sweeper",
    "Thundurus": "Sweeper",
    "Staraptor": "Wallbreaker",
    "Vileplume": "Wall",
    "Frosmoth": "Sweeper",
    "Pincurchin": "Utility",
    "Feraligatr": "Sweeper",
    "Rotom-Heat": "Pivot",
    "Decidueye-Hisui": "Wallbreaker",
    "Ambipom": "Pivot",
    "Klefki": "Utility",
    "Politoed": "Weather Setter",
    "Slowbro": "Pivot",
    "Arcanine": "Pivot",
    "Iron Jugulis": "Sweeper",
    "Vikavolt": "Wallbreaker",
    "Eelektross": "Pivot",
    "Diancie": "Utility",
    "Smeargle": "Hazard Lead",
    "Inteleon": "Sweeper",
    "Lycanroc-Dusk": "Hazard Lead",
    "Malamar": "Sweeper",
    "Overqwil": "Hazard Stack",
    "Grafaiai": "Utility",
    "Goodra": "Wall",
    "Heracross": "Wallbreaker",
    "Typhlosion-Hisui": "Wallbreaker",
    "Scream Tail": "Utility",
    "Cyclizar": "Pivot",
    "Tsareena": "Hazard Removal",
    "Pikachu": "Unviable",
    "Yanmega": "Sweeper",
    "Cinccino": "Sweeper",
    "Mienshao": "Pivot",
    "Hitmonlee": "Sweeper",
    "Cetitan": "Sweeper",
    "Azelf": "Attacker",
    "Entei": "Wallbreaker",
    "Electivire": "Attacker",
    "Exeggutor": "Wallbreaker",
    "Drifblim": "Utility",
    "Braviary-Hisui": "Wallbreaker",
    "Lapras": "Wall",
    "Flygon": "Pivot",
    "Enamorus-Therian": "Wall",
    "Leavanny": "Unviable",
    "Dragalge": "Wallbreaker",
    "Dusclops": "Wall",
    "Scrafty": "Sweeper",
    "Scovillain": "Sweeper",
    "Arboliva": "Wall",
    "Meloetta": "Wallbreaker",
    "Brambleghast": "Wallbreaker",
    "Electrode-Hisui": "Hazard Lead",
    "Slowbro-Galar": "Wallbreaker",
    "Minior": "Sweeper",
    "Typhlosion": "Wallbreaker",
    "Necrozma": "Attacker",
    "Cobalion": "Pivot",
    "Houndstone": "Sweeper",
    "Primeape": "Wallbreaker",
    "Leafeon": "Sweeper",
    "Glastrier": "Wallbreaker",
    "Revavroom": "Wallbreaker",
    "Wo-Chien": "Wall",
    "Scyther": "Pivot",
    "Raikou": "Attacker",
    "Cryogonal": "Utility",
    "Beartic": "Sweeper",
    "Decidueye": "Wallbreaker",
    "Farigiraf": "Utility",
    "Bellibolt": "Wall",
    "Abomasnow": "Weather Setter",
    "Avalugg": "Wall",
    "Regice": "Wall",
    "Slaking": "Unviable",
}

role_map.update({
    "Pelipper": "Rain Setter",
    "Politoed": "Rain Setter",
    "Torkoal": "Sun Setter",
    "Ninetales": "Sun Setter",
    "Tyranitar": "Sand Setter",
    "Hippowdon": "Sand Setter",
    "Ninetales-Alola": "Snow Setter",
    "Abomasnow": "Snow Setter",

    "Barraskewda": "Rain Sweeper",
    "Kingdra": "Rain Sweeper",
    "Basculegion": "Rain Sweeper",

    "Walking Wake": "Sun Sweeper",
    "Venusaur": "Sun Sweeper",
    "Lilligant-Hisui": "Sun Sweeper",
    "Excadrill": "Sand Sweeper",

    "Cetitan": "Snow Sweeper",
})